### ISSUE TITLE
Issues Billing

### ISSUE THREAD

**Issue by ravish1729** [lighthouse-web3/contracts#24]
isSubscriptionActive should be read command instead of write

**Comment by xlassix** [comment]
I agree, I just had to add a condition to trigger the subscription recursive payment on request. I was hoping we could integrate with chainlink to trigger the recursive deduction and move that clause out of `isSubscriptionActive` function

**Comment by xlassix** [comment]
Check  `subscriptionStatus` that's the function you are looking for
